version: '3.7'

volumes:
  caddy_data: {}

services:
  node_app:
    image: alframi410/code_crafters_node_app

  caddy:
    image: alframi410/code_crafters_caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy_data:/data
    configs:
      - source: caddy_config
        target: /etc/Caddyfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
